### ISSUE TITLE
[question] Update the API usage in this demo?

### ISSUE THREAD

**Issue by alvov** [mdn/panner-node#1]
This demo is great for understanding how to use `PannerNode` and `AudioListener` together, and how the whole 3d sound positioning works, but I find the use of deprecated methods in it a little bit confusing. Would it be ok to update this example code?

I'm talking about `setOrientation` and `setPosition` methods, which are deprecated in [current draft of the spec](https://webaudio.github.io/web-audio-api/), `setVelocity`, which can be omitted at all, as we can control the velocity gain of the boombox panner by changing its distance from the listener alone. Also the `dopplerFactor` and `speedOfSound` attributes of `AudioListener` may be completely removed, as they are not mentioned in the new spec even as deprecated attributes.

Thanks in advance!

**Comment by chrisdavidmills** [comment]
I have updated the demo to account for these changes. I'm also working on updating the relevant MDN docs. The trouble is that Firefox currently seems to support the old methods (e.g. `setOrientation()`) whereas Chrome now supports the newer properties (e.g. `forwardX`). I've added in some feature detection code to make it work in both cases.

**Comment by alvov** [comment]
@chrisdavidmills thanks a lot! Hopefully the FF50 update will ship the newer `PannerNode` interface this month.
Also, just to mention, as you removed `setVelocity` method, the `xVel` and `zVel` variables seem to become unused now.

**Comment by chrisdavidmills** [comment]
Ahhhh, good catch, thanks! I've updated the code again, and the createPanner page on MDN.
